routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CurriculumsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/inicio', function(){
    return view('home');
});

Route::get('/nosotros', function(){
    return view('team');
});

Route::get('/contacto', function(){
    return view('contacto');
});

Route::get('/contenido', function(){
    return view('blog');
});

Route::get('/galeria', function(){
    return view('galeria');
});

Route::get('/reservaciones', function(){
    return view('reservaciones');
});

Route::get('/lista_curriculums', function(){
  return view('lista_curriculums');
});
/*
Route::get('quierover', function(){
    return view('curriculums');
  });

Route::get('/prueba', function(){
    return view('formdos');
});

Route::get('/bolsa', function(){
    return view('registro_curriculum');
});

Route::get('registro_curriculums',[CurriculumsController::class,'create']);
Route::post('registro_curriculums',[CurriculumsController::class,'store']);
*/

Route::resource('curriculums','CurriculumsController');
/*
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
*/

app/Curriculums.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Curriculums extends Model
{
    protected $fillable=['nombre','apellido','edad','cargo','foto','email'];
}

app/Reservaciones.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reservaciones extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CurriculumsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CurriculumsRequest;
use App\Curriculums;

class CurriculumsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $curriculums= Curriculums::all();
        return view('lista_curriculums', compact('curriculums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('curriculums');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CurriculumsRequest $datos)
    {
        $curriculums=new Curriculums();
        $curriculums->nombre=$datos->nombre;
        $curriculums->apellido=$datos->apellido;
        $curriculums->edad=$datos->edad;
        $curriculums->cargo=$datos->cargo;
        $datos->imagen->store(config('misimg.path'), 'public');
        $curriculums->foto='foto/' .$datos->imagen->hashName();
        $curriculums->email=$datos->email;
        $curriculums->save();
        return  redirect()->route('curriculums.index')->with('mensaje','El curriculum fue agregado correctamente');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Curriculums $curriculum)
    {
        return view('detalle_curriculum',compact('curriculum'));


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Curriculums $curriculum)
    {
        //
        return view('editar', compact('curriculum'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CurriculumsRequest $datos, Curriculums $curriculum)
    {
        $curriculum->update($datos->all()); 
        return redirect()->route('curriculums.index')->with('mensaje','El curriculum ha sido editado correctamente');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Curriculums $curriculum)
    {
        //
        $curriculum->delete();
        return back()->with('mensaje','El curriculum ha sido eliminado correctamente');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ReservacionesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ReservacionesController extends Controller
{
    //
}

resources/views/detalle_curriculum.blade.php
<html lang="es">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Bolsa de Trabajo</title>
      <!-- Google Fonts -->
      <link rel='stylesheet' id='caverta-font-css'  href='http://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700%7CLora:400,700,400i,700i' type='text/css' media='all' />
      <!-- Bootstrap CSS -->
      <link rel='stylesheet' id='bootstrap-css'  href="{{URL::asset('assets/css/bootstrap/css/bootstrap.min.css')}}" type='text/css' media='all' />
      <!-- Font Awesome Icons CSS -->
      <link rel='stylesheet' id='font-awesome'  href="{{URL::asset('assets/css/fontawesome/css/font-awesome.min.css')}}" type='text/css' media='all' />
      <!-- Owl Carousel -->
      <link rel='stylesheet' id='owl-carousel'  href="{{URL::asset('assets/js/owl-carousel/owl.carousel.min.css')}}" type='text/css' media='all' />
      <!-- Main CSS File -->
      <link rel='stylesheet' id='caverta-style-css'  href="{{URL::asset('style.css')}}" type='text/css' media='all' />
      <!-- favicons -->
      <link rel="icon" href="{{URL::asset('assets/images/icons/favicon-32x32.png')}}" sizes="32x32" />
      <link rel="icon" href="{{URL::asset('assets/images/icons/favicon-192x192.png')}}" sizes="192x192" />
      <link rel="apple-touch-icon-precomposed" href="{{URL::asset('assets/images/icons/favicon-180x180.png')}}" />
   </head>
   <body class="home">
      <div class="menu-mask"></div>
      <!-- MOBILE MENU HOLDER -->
      <div class="mobile-menu-holder">
         <div class="modal-menu-container">
            <div class="exit-mobile">
               <span class="icon-bar1"></span>
               <span class="icon-bar2"></span>
            </div>
            <!-- MOBILE MENU -->
            <ul class="menu-mobile">
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/inicio'); ?>">Inicio</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/contenido'); ?>">Blog</a>
					
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/nosotros'); ?>">Nuestro Equipo</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/galeria'); ?>">Galería</a>
					</li>
               <li class="menu-item menu-item-has-children">
						<a href="<?= url('/reservaciones'); ?>">Reservaciones</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/contacto'); ?>">Contacto</a>
					</li>
            </ul>
            <!-- /MOBILE MENU -->
         </div>
         <!-- modal-menu-container -->
         <div class="menu-contact"><div class="mobile-btn"> <a href="#" class="view-more">Reservar</a></div>
            <ul class="mobile-contact">
               <li class="mobile-address">Calle 20<br />
                  Cancún, Quintana Roo CP: 77535
               </li>
               <li class="mobile-phone">9981801087</li>
               <li class="mobile-email">cassandratello25@gmail.com</li>
            </ul>
            <ul class="social-media">
               <li><a class="social-facebook" href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a class="social-twitter" href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                  <li><a class="social-tripadvisor" href="#" target="_blank"><i class="fab fa-tripadvisor"></i></a></li>
                  <li><a class="social-instagram" href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                  <li><a class="social-pinterest" href="#" target="_blank"><i class="fab fa-pinterest"></i></a></li>
            </ul>
         </div>
         <!-- /menu-contact-->
      </div>
      <!-- /MOBILE MENU HOLDER -->
      <!-- HEADER -->
      <header id="header-1" class="headerHolder header-1">
         <div class="nav-button-holder">
            <button type="button" class="nav-button">
            <span class="icon-bar"></span>
            </button>
         </div>
         <!-- /nav-button-holder-->
         <!-- LOGO -->
         <div class="logo logo-1"><a href="<?= url('/inicio'); ?>"><img class="img-fluid" src="{{URL::asset('assets/images/caverta-logo.png')}}" alt="Caverta" /></a></div>
         <!-- MENU -->
         <nav class="nav-holder nav-holder-1">
            <ul class="menu-nav menu-nav-1">
              <li class="menu-item menu-item-has-children">
						<a href="<?= url('/inicio'); ?>">Inicio</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/contenido'); ?>">Blog</a>
					
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/nosotros'); ?>">Nuestro Equipo</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/galeria'); ?>">Galería</a>
					</li>
               <li class="menu-item menu-item-has-children">
						<a href="<?= url('/reservaciones'); ?>">Reservaciones</a>
					</li>
					<li class="menu-item menu-item-has-children">
						<a href="<?= url('/contacto'); ?>">Contacto</a>
					
					</li>
            </ul>
         </nav>
         <!-- /MENU --> 
         <div class="btn-header">
            <p><a href="<?= url('/reservaciones'); ?>" class="view-more">Reservar</a></p>
         </div>
      </header>
      <!-- /HEADER -->
      <!-- TOP IMAGE -->
      <section class="topSingleBkg topPageBkg topPageCustomH">
         <div class="item-img top-contact"></div>
         <div class="inner-desc">
            <h1 class="post-title single-post-title">Permítenos Ayudarte</h1>
            <span class="post-subtitle"> Deja tus Datos y/o Curriculum</span>
         </div>
      </section>
      <!-- /TOP IMAGE --> 
      <!-- /WRAP CONTENT -->
      <div id="wrap-content" class="page-content custom-page-template">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div id="reservation-holder">
                     <div class="smalltitle margin-b16">Lista de Curriculums</div>
                        <h2> Detalle de curriculum</h2>
                               
                        <img src="../{{$curriculum->foto}}" width="150" height="200" >
                        <td><p>Nombre: {{$curriculum->nombre}}</p></td>
                        <td><p>Apellido: {{$curriculum->apellido}}</p></td>
                        <td><p>Edad: {{$curriculum->edad}}</p></td>
                        <td><p>Cargo: {{$curriculum->cargo}}</p></td>
                        <td><p>Email: {{$curriculum->email}}</p></td>
                        <td><a href="{{route('curriculums.edit', $curriculum->id)}}">Editar</a></td>
                        <td>
                           <form action="{{route('curriculums.destroy',$curriculum->id)}}"method="post";>
                              @csrf
                              @method('Delete')
                              <button type="submit">Eliminar</button>
                           </form>
                        </td>                          
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- /WRAP CONTENT -->
      <!-- FOOTER -->
      <footer>
         <div class="container">
            <div class="footer-widgets">
               <div class="row">
                  <!-- FOOTER COLUMN 1 -->
                  <div class="col-md-3">
                     <div class="foo-block">
                        <div id="text-2" class="widget widget-footer widget_text">
                           <div class="textwidget">
                              <p><img class="size-full wp-image-665" src="{{URL::asset('assets/images/caverta-logo2.png')}}" alt="" width="143" height="51"></p>
                              <p>Para una experiencia gastronómica verdaderamente memorable, la comida y el ambiente se combinan tan cuidadosamente como la comida y el vino.</p>
                           </div>
                        </div>
                     </div>
                     <!--foo-block-->
                  </div>
                  <!--col-md-3-->
                  <!-- FOOTER COLUMN 2 -->
                  <div class="col-md-3">
                     <div class="foo-block">
                        <div id="text-3" class="widget widget-footer widget_text">
                           <h5 class="widgettitle"><span>Dirección</span></h5>
                           <div class="textwidget">
                            <p>Calle 20<br>
                                Cancún, Quintana Roo CP: 77535
                             </p>
                             <p>Cel: 9981801087<br>
                                Correo: cassandratello25@gmal.com
                            </p>
                           </div>
                        </div>
                     </div>
                     <!--foo-block-->
                  </div>
                  <!--col-md-3-->
                  <!-- FOOTER COLUMN 3 -->
                  <div class="col-md-3">
                     <div class="foo-block">
                        <div id="text-4" class="widget widget-footer widget_text">
                           <h5 class="widgettitle"><span>Horarios</span></h5>
                           <div class="textwidget">
                            <p>Lunes – Domingo<br>
                                Almuerzo: 12PM – 2PM<br>
                                Cena: 6PM – 10PM
                             </p>
                             <p>Hora Feliz: 4PM – 6PM</p>
                           </div>
                        </div>
                     </div>
                     <!--foo-block-->
                  </div>
                  <!--col-md-3-->
                  <!-- FOOTER COLUMN 4 -->
                  <div class="col-md-3">
                     <div class="foo-block foo-last">
                        <div id="text-5" class="widget widget-footer widget_text">
                           <h5 class="widgettitle"><span>Más información</span></h5>
                           <div class="textwidget">
                              <ul>
                                <li><a href="#">Recomendaciones</a></li>
                                <li><a href="#">Actividades recreativas</a></li>
                                <li><a href="#">Política de privacidad</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <!--foo-block-->
                  </div>
                  <!--col-md-3-->
               </div>
               <!--row-->
            </div>
            <!-- footer-widgets -->
            <div class="copyright">
               <!-- COPYRIGHT -->
               <div class="footer-copy">
                  <p>Copyright © 2021, Banquetes Gourmet . Designed by puesyo</p>
               </div>
               <!-- SOCIAL ICONS -->
               <ul class="footer-social">
                  <li><a class="social-facebook" href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a class="social-twitter" href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                  <li><a class="social-tripadvisor" href="#" target="_blank"><i class="fab fa-tripadvisor"></i></a></li>
                  <li><a class="social-instagram" href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                  <li><a class="social-pinterest" href="#" target="_blank"><i class="fab fa-pinterest"></i></a></li>
               </ul>
            </div>
            <!--copyright-->
         </div>
         <!--container-->
      </footer>
      <!-- /FOOTER -->
      <div class="scrollup">
         <a class="scrolltop" href="#">
         <i class="fa fa-chevron-up"></i>
         </a>
      </div>
      <!-- JS --> 
      <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
      <script src="{{URL::asset('assets/js/jquery-migrate.min.js')}}"></script>
      <script src="{{URL::asset('assets/css/bootstrap/js/popper.min.js')}}"></script>
      <script src="{{URL::asset('assets/css/bootstrap/js/bootstrap.min.js')}}"></script>
      <script src="{{URL::asset('assets/js/jquery.easing.min.js')}}"></script>
      <script src="{{URL::asset('assets/js/jquery.fitvids.js')}}"></script>
      <script src="{{URL::asset('assets/js/owl-carousel/owl.carousel.min.js')}}"></script>
      <script src="{{URL::asset('assets/js/jquery.magnific-popup.min.js')}}"></script>
      <!-- MAIN JS -->
      <script src="{{URL::asset('assets/js/init.js')}}"></script>
      <!-- CONTACT FORM JS -->
      <script src="{{URL::asset('assets/js/jquery.form.min.js')}}"></script>
      <script src="{{URL::asset('assets/js/contactform-home.js')}}"></script>
   </body>
</html>
      

resources/views/home.blade.php
@extends('layouts.base')

@section('contenido')

@endsection

resources/views/lista_curriculums.blade.php
@extends('layouts.cont')

@section('contenido')
      <div id="wrap-content" class="page-content custom-page-template">
        <div class="container">
           <div class="row">
              <div class="col-md-12">
                  <div id="reservation-holder">
                    <div class="smalltitle margin-b16">Lista de Curriculums</div>
                    <a href="{{ route('curriculums.create')}}">Agregar Curriculum</a>
                    @if (session()->has('mensaje'))
                       <p style="color: red">{{session('mensaje')}}</p>
                    @endif
                    @foreach ($curriculums as $curriculum)
                       <table class="Taliniado">
                           <tr>
                              <th>Nombre</th> 
                              <p></p>
                              <th>Apellido</th>
                              <p></p>
                              <th>Edad</th>
                              <p></p>
                              <th>Cargo</th>
                              <p></p>
                              <th>Email</th>
                              <p></p>
                            </tr>
                            <tr>
                              <img src="../{{$curriculum->foto}}" alt="" >
                              <td><p>{{$curriculum->nombre}}</p></td>
                              <td><p>{{$curriculum->apellido}}</p></td>
                              <td><p>{{$curriculum->edad}}</p></td>
                              <td><p>{{$curriculum->cargo}}</p></td>
                              <td><p>{{$curriculum->email}}</p></td>
                              <td><a href="{{route('curriculums.show', $curriculum->id)}}">Info</a></td>
                              <td><a href="{{route('curriculums.edit', $curriculum->id)}}">Editar</a></td>
                              <td>
                                  <form action="{{route('curriculums.destroy',$curriculum->id)}}"method="post";>
                                       @csrf
                                       @method('Delete')
                                     <button type="submit">Eliminar</button>
                                     
                                    </form>
                              </td>
                              
                              
                           </tr>
                        
                        </table>

                     @endforeach
                   
                  </div>
              </div>
          </div>
       </div>
    </div> 

@endsection